### ISSUE TITLE
CRAVEX: Export VEX document: CSAF

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/dejacode#107]
Export the results of the vulnerabilities triage and processing as CSAF VEX document

**Comment by DennisClark** [comment]
Looking for current example CSAF files with actual data and for a definitive version of the current specfification.

Also, for reference see 
https://github.com/oasis-tcs/csaf   and
https://www.redhat.com/en/blog/common-security-advisory-framework-csaf-beta-files-now-available  (2022-06-17).

**Comment by DennisClark** [comment]
Specific public examples of CSAF 2.0 documents from Schneider Electric can be found here: 
https://www.se.com/ww/en/work/support/cybersecurity/security-notifications.jsp 

One example is attached.  

[sevd-2023-101-05.json](https://github.com/user-attachments/files/15743701/sevd-2023-101-05.json)

**Comment by pombredanne** [comment]
I am not sure this requires mucho design, does it? Based on what we have for CycloneDX this should be easy.

**Comment by tdruez** [comment]
https://oasis-open.github.io/csaf-documentation/
