### ISSUE TITLE
CRAVEX: Create usage documentation

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/dejacode#109]
Create and publish usage and reference documentation

**Comment by DennisClark** [comment]
We'll need a Reference document to explain the overall concepts and one or more how-to documents to explain the details.

**Comment by tdruez** [comment]
Added in https://github.com/aboutcode-org/dejacode/pull/212

2 new sections are available:
- [Reference: Vulnerability Management](https://dejacode.readthedocs.io/en/latest/reference-vulnerability-management.html)
- [How To 4 - Product Vulnerability Analysis](https://dejacode.readthedocs.io/en/latest/howto-4-product-vulnerability-analysis.html)
