### ISSUE TITLE
Add filters/search for the Product Inventory 

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/dejacode#112]
When working with hundred of Inventory Items you need the capability to search and filter by Item name.
Some common use cases are:
- Search/filter by package type
- Search/filter by package or component name.

**Comment by DennisClark** [comment]
Enhancement suggestion noted.  As a short-term workaround, please note that you can use the text search feature of your browser to look for a package.

**Comment by tdruez** [comment]
@mjherzog Inventory tab search was added along in https://github.com/nexB/dejacode/issues/3 PR https://github.com/nexB/dejacode/pull/24

You can now use it to search the following fields:

- `component__name`
- `component__version`
- `package__filename`
- `package__type`
- `package__namespace`
- `package__name`
- `package__version`
- `license_expression`
- `notes`
- `extra_attribution_text`
- `feature`
- `issue_ref`

This should cover the basics but we can keep this issue opened for improvements regarding the Ui and active filters.

**Comment by tdruez** [comment]
Added the current active filter in the Inventory tab UI.
