### ISSUE TITLE
Add option to replace previous Package/Component version in "Add to Product"

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/dejacode#12]
When adding a package to a product after upgrading the version in the codebase:
- I'm adding this package to DejaCode
- Get the automated scan results and generate an ABOUT file that I place along the dist package in the codebase
- Use "Add to Product" to assign this package to my current product/version
- I need to manually remove the previous `ProductPackage` entry and I lost field values such as the `purpose`

We could add an option to the "Add to Product", to enable automatic replacement of the ProductPackage entry, keeping some of the field values such as `purpose`.

This would only be applied in case there's 1 entry with the same purl (different version).

@DennisClark Let me know your thoughts on this.

**Comment by tdruez** [comment]
@DennisClark The feature is only available when selecting 1 or more Packages from the list and using the "Add to Product" action.

I'm not sure how we would be able to add this to the single package "Add to product" form that displays a complex form including all the relationship fields without a value. 
Assuming the user would set any of those fields and select the "replace existing version", how would we deal with those values? It's unlikely that the user knows about any existing values on the existing version, overriding may be unwanted.

**Comment by DennisClark** [comment]
@tdruez   thanks fro the explanation; I'll give it another try.

**Comment by DennisClark** [comment]
@tdruez   looks good in Staging Starship, and the explanatory text for the new capability is excellent.  thanks.
