### ISSUE TITLE
BUG: Clicking on a VCID in the Product Vulnerabilities tab gets a 404

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/dejacode#176]
**Describe the bug**
In both production and staging, when I open any Product with Vulnerabilities, and click on any VCID in the Vulnerabilities tab, I get a 404.  Staging has more detail (debug mode); see screenshot.  

Note that the DejaCode Integrations Status form shows everything Configured and Available.

I also confirmed that the VCIDs that I tested were available in VCIO; for example: 
https://public.vulnerablecode.io/vulnerabilities/search?search=VCID-hh72-ne73-aaak

**To Reproduce**
Sign in to the nexB dataspace.
Open Starship Widget Framework 9.7
Go to the Vulnerabilities tab
Click on the first VCID 

**Expected behavior**
The Vulnerability should be presented in VCIO as in 
https://public.vulnerablecode.io/vulnerabilities/search?search=VCID-hh72-ne73-aaak

**Screenshots**
<img width="1040" alt="VCID-404" src="https://github.com/user-attachments/assets/6aae1422-1b21-4bc9-bfbf-b1e3ed5a650c">

**Comment by tdruez** [comment]
Fix merged and deployed.
