### ISSUE TITLE
Bug: SPDX file generated for DejaCode 5.2 fails to validate

### ISSUE THREAD

**Issue by DennisClark** [aboutcode-org/dejacode#180]
The attached file dejacode_nexb_product_dejacode_5.2.spdx.json was generated by SCIO and it fails to validate at  

https://tools.spdx.org/app/validate/ 

See screenshot.
<img width="1061" alt="validate-error-dejacode_nexb_product_dejacode_5 2 spdx json" src="https://github.com/user-attachments/assets/ffcf6b2d-a993-49f9-a27b-1feb7526da34">

**Comment by tdruez** [comment]
Transferred to the DejaCode repo.

**Comment by DennisClark** [comment]
On staging, I generated a new SPDX file for DejaCode 5.2, and it validates successfully.  

<img width="978" alt="Validate SPDX from DejaCode 2024-10-22 at 09 54 30" src="https://github.com/user-attachments/assets/7b680fd3-ecad-41a3-be89-69eeb9cd05c7">

**Comment by tdruez** [comment]
Fix deployed.
