### ISSUE TITLE
Enhancement request: Make packages the first/primary field for the Product Vulnerabilities tab

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/dejacode#192]
The Vulnerabilities tab for Products currently displays Vulnerability as the first field with Affected Packages on the far left.
This makes it difficult to see vulnerabilities by package esp. since there is no option to sort by Affected Packages.
See the ScanCode.io 33.0.0-dev for a good example where there are several vulnerabilities for pkg:pypi/django@5.0.
Seeing the set of vulnerabilities for a given package seems like a/the primary use case for this data.
It would be nice to also allow sorting by Vulnerability or Affected Packages.

**Comment by DennisClark** [comment]
@mjherzog   Please note that one can filter by packages with vulnerabilities on the Product Inventory tab; just click the little "bug" icon in the "Item" heading.

**Comment by mjherzog** [comment]
Good to know, but the Vulnerabilities tab has much more interesting information. Adding just the sort options could suffice, but my understanding is that for AboutCode in general we want to emphasize organizing the data by Package.

**Comment by DennisClark** [comment]
@mjherzog  I agree with your suggestions, thanks.

**Comment by tdruez** [comment]
The Vulnerabilities tab layout was updated in https://github.com/aboutcode-org/dejacode/pull/218 for https://github.com/aboutcode-org/dejacode/issues/102

The primary column is now the package.
![Screenshot 2024-12-27 at 21 28 09](https://github.com/user-attachments/assets/b08828a0-a363-4b46-ba6e-527ad0987de0)
