### ISSUE TITLE
BUG: DejaCode does not allow to use TLS for Redis connection

### ISSUE THREAD

**Issue by ghsa-retrieval** [aboutcode-org/dejacode#207]
**Describe the bug**
Currently DejaCode does not use TLS when connecting to Redis and does not offer an option to enable it. This is an issue when attempting to deploy DejaCode with Redis hosted on a separate system (e.g. a cloud deployment with ElastiCache), unlike the default docker-compose deployment.

The root cause is that DejaCode uses django-rq, which disables TLS by default unless specific options are passed.

As can be seen in the following lines, only `HOST`,  `PORT`, `PASSWORD`, and `DEFAULT_TIMEOUT` are being set by DejaCode:
https://github.com/aboutcode-org/dejacode/blob/9eb7fb78a386807966f8b04627fe33ec8926afc1/dejacode/settings.py#L440-L447

Without either `SSL` set to `True` or `URL` set to contain `rediss://` (two s!), it will not use TLS:
https://github.com/rq/django-rq/blob/cd05d2f427e6bd54ce91f78549f05884fa96753e/django_rq/queues.py#L137

**To Reproduce**
See above.

**Expected behavior**
DejaCode should provide an option to enable TLS for the REDIS connection.

**Screenshots**
Not applicable

**Context (OS, Browser, Device, etc.):**
Not applicable

**Comment by tdruez** [comment]
@ghsa-retrieval Thanks for the suggestion, see https://github.com/aboutcode-org/dejacode/pull/208 for proposed changes.

**Comment by tdruez** [comment]
@ghsa-retrieval Great, I'll wait for your test results before merging this.

**Comment by tdruez** [comment]
@ghsa-retrieval Thanks for your confirmation. PR merged in main :) 
SCIO will follow.
