### ISSUE TITLE
BUG: cgi module deprecated, removed in python 3.13

### ISSUE THREAD

**Issue by L3ChatNoir** [aboutcode-org/dejacode#216]
The cgi module used in [download.py](https://github.com/aboutcode-org/dejacode/blob/main/dejacode_toolkit/download.py) has been removed in python 3.13. 

Proposed Solutions:
- Use [legacy-cgi](https://pypi.org/project/legacy-cgi), [docs 3.13/cgi](https://docs.python.org/3.13/library/cgi.html)
- Alternative (like email package) in [docs 3.12/cgi](https://docs.python.org/3.12/library/cgi.html#cgi.parse_header)
- Maybe django have a function for replace cgi

**Comment by tdruez** [comment]
> Maybe django have a function for replace cgi

Yes, the solution is to replace `cgi` by `django.utils.http.parse_header_parameters`.
See https://github.com/aboutcode-org/scancode.io/pull/1469/files#diff-7a36c56352327848814ca31d0ce6c698852859adce859ec6570839f5555d04ba for example.

Only Python3.12 is officially supported for DejaCode at the moment though.

**Comment by L3ChatNoir** [comment]
>I missclick. I didn't want to close the issue. 

If "Only Python3.12 is officially supported for DejaCode at the moment though".
I think that  [setup.cfg](https://github.com/aboutcode-org/dejacode/blob/main/setup.cfg) need a update to specify the python version. 

```
python_requires = >=3.12, <3.13
```

**Comment by tdruez** [comment]
@L3ChatNoir Thanks for the suggestion. Done in https://github.com/aboutcode-org/dejacode/commit/79699bca5bf8f2004dd883e8f2e913ba3a28f8ce
